"""empty message

Revision ID: 42806ac52679
Revises: 46c108e0b718
Create Date: 2023-04-18 11:42:44.421562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42806ac52679'
down_revision = '46c108e0b718'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
